In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import os
import time
import pathlib

python_path = pathlib.Path('.').absolute().parent/'python'
os.sys.path.insert(1, str(python_path))

In [3]:
## This is demo for kuka reaching a desired point with diff_qp
## Author : Avadesh Meduri
## Date : 25/02/2022
import time
import numpy as np
import pinocchio as pin
from robot_properties_kuka.config import IiwaConfig

import meshcat
import meshcat.transformations as tf
import meshcat.geometry as g

from vocam.diff_pin_costs import DiffFrameTranslationCost, DiffFrameVelocityCost
from vocam.inverse_qp import IOC

import torch
from torch.autograd import Function
from torch.nn import functional as F

In [4]:
robot = IiwaConfig.buildRobotWrapper()
model, data = robot.model, robot.data
f_id = model.getFrameId("EE")

In [5]:
viz = pin.visualize.MeshcatVisualizer(robot.model, robot.collision_model, robot.visual_model)
viz.initViewer(open=False)
viz.loadViewerModel()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7004/static/


In [48]:
dtc = DiffFrameTranslationCost.apply
dvc = DiffFrameVelocityCost.apply

def quadratic_loss(q_pred, x_des, nq, n_col):
    loss = 4.5e1*torch.linalg.norm(dtc(q_pred[-2*nq:], model, data, f_id) - x_des)
    loss += 1.5e0*torch.linalg.norm(dvc(q_pred[-2*nq:], torch.zeros(nq), model, data, f_id)) # asking for zero velocity
    loss += 1e-2*torch.linalg.norm(q_pred[-2*nq:-nq]) # joint regularization
    
    for i in range(n_col):    
        loss += 1e0*torch.linalg.norm(dtc(q_pred[(3*i)*nq: (3*i+2)*nq], model, data, f_id) - x_des)
        loss += 5e-1*torch.linalg.norm(dvc(q_pred[(3*i)*nq: (3*i+2)*nq], q_pred[(3*i+2)*nq:(3*i+3)*nq], model, data, f_id)) # asking for zero velocity
        loss += 1e-2*torch.linalg.norm(q_pred[(3*i+2)*nq: (3*i+3)*nq]) # control regularization
        loss += 2e-1*torch.linalg.norm(q_pred[(3*i+1)*nq: (3*i+2)*nq]) # velocity regularization
        loss += 3e-3*torch.linalg.norm(q_pred[(3*i)*nq: (3*i+1)*nq]) # joint regularization
        loss += 2e-3*torch.linalg.norm(q_pred[(3*i)*nq+3: (3*i+1)*nq])
        loss += 4e-3*torch.linalg.norm(q_pred[(3*i)*nq+5])
        
        if i < n_col - 1:
            loss += 5e-2*torch.linalg.norm(torch.subtract(q_pred[(3*i+2)*nq: (3*i+3)*nq], \
                                                          q_pred[(3*i+5)*nq: (3*i+6)*nq]))

    return loss

In [49]:
nq = model.nq
nv = model.nv
q0 = [np.pi/16.0, -np.pi/16.0, 0, 0, 0, 0, 0]
x_init = np.concatenate([q0, pin.utils.zero(model.nv)])

n_col = 5
u_max = [2.5,2.5,2.5, 1.5, 1.5, 1.5, 1.0]
dt = 0.05

isvec = True
lr = 1e-1
max_eps = 100



In [84]:
buffer_size = 2000
f_name = "5"
n_mpc = 15

x_train_init = torch.zeros((buffer_size,len(x_init)))
x_train_des = torch.zeros((buffer_size, 3))

n_vars = 3*nq*n_col + 2*nq
if not isvec:
    y_train = torch.zeros((buffer_size, n_vars**2 + n_vars))
else:
    y_train = torch.zeros((buffer_size, 2*n_vars))

q_des_arr = np.array([[2.1789238e-02,  3.3214998e-01, -1.4518893e-04, -8.7141126e-01,
                          6.0329604e-01, -1.3965217e-03,  1.4794523e-04],
                      [1.3737, 0.9711, 1.6139, 1.2188, 1.5669, 0.1236, 0.2565]])
# x_des_arr = torch.tensor([[0.5, -0.4, 0.7], [0.6, 0.4, 0.5]])
x_des_arr = torch.tensor([[0.3, -0.3, 0.7], [0.3, 0.3, 0.5]])



In [ ]:
for k in range(buffer_size):
    ioc = IOC(n_col, nq, u_max, dt, eps = 1.0, isvec=isvec)
    optimizer = torch.optim.Adam(ioc.parameters(), lr=lr)

    if k % n_mpc == 0:
        
        r = 0.4*np.random.rand(1)+0.45
        theta = 0.7*np.pi*np.random.rand(1)
        x_des = torch.squeeze(torch.tensor([r*np.sin(theta), r*np.cos(theta), 0.6*np.random.rand(1)+0.2]))

        viz.viewer["box"].set_object(g.Sphere(0.05), 
                         g.MeshLambertMaterial(
                             color=0xff22dd,
                             reflectivity=0.8))
        viz.viewer["box"].set_transform(tf.translation_matrix(x_des.detach().numpy()))
    
    if np.random.randint(2) == 0 and k % n_mpc == 0:
            x_init = np.zeros(2*nq)
            x_init[0:nq] = q_des_arr[0] + 0.3*2*(np.random.rand(nq) - 0.5)
            x_init[0] -= 2*1.2*(np.random.rand(1) - 0.5)
            x_init[nq:] = 0.4*2*(np.random.rand(nv) - 0.5)
    
    else:
        x_init = x_pred[-2*nq:]

    x_train_init[k] = torch.tensor(x_init)
    x_train_des[k] = x_des
    
    i = 0
    loss = 1000.
    old_loss = 10000.
    
    while loss > 0.03 and i < max_eps and abs(old_loss - loss) > 5e-4:
        x_pred = ioc(x_init) 
        old_loss = loss
        loss = quadratic_loss(x_pred, x_des, nq, n_col)
        print("Index :" + str(k) + "/" + str(buffer_size) + " Iteration :" + str(i) + "/" + str(max_eps) +  " loss is : " + str(loss.detach().numpy()), end = '\r', flush = True)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        i += 1
    
    x_pred = ioc(x_init).detach().numpy()
    for i in range(n_col+1):
        q = x_pred[3*nq*i:3*nq*i + nq]
        dq = x_pred[3*nq*i + nq:3*nq*i + 2*nq]

        pin.forwardKinematics(model, data, q, dq, np.zeros(nv))
        pin.updateFramePlacements(model, data)

        viz.display(q)
        time.sleep(0.01)
    
    # storing the weights and x_nom
    y_train[k] = torch.hstack((ioc.weight.flatten(), ioc.x_nom))

    if k % 100 == 0 and k:
        x_train = torch.hstack((x_train_init, x_train_des)).float()
        torch.save(x_train[0:k], "../data/x_train" + str(f_name) + ".pt")
        torch.save(y_train[0:k], "../data/y_train" + str(f_name) + ".pt")

x_train = torch.hstack((x_train_init, x_train_des)).float()
torch.save(x_train[0:k], "../data/x_train" + str(f_name) + ".pt")
torch.save(y_train[0:k], "../data/y_train" + str(f_name) + ".pt")

In [109]:
# x_train = torch.hstack((x_train_init, x_train_des)).float()
# y_train = y_train.detach().float()

# torch.save(x_train, "./data/x_train3.pt")
# torch.save(y_train, "./data/y_train3.pt")

In [22]:
x_train = torch.load("../data/x_train4.pt")
y_train = torch.load("../data/y_train4.pt")

# x_train_loaded2 = torch.load("./data/x_train2.pt")
# y_train_loaded2 = torch.load("./data/y_train2.pt")

# x_train = torch.vstack((x_train_loaded, x_train))
# y_train = torch.vstack((y_train_loaded, y_train))

# x_train = torch.vstack((x_train_loaded2, x_train))
# y_train = torch.vstack((y_train_loaded2, y_train))

print(x_train.shape)

torch.Size([5, 17])


In [17]:
path = "../data/data_500_12.pt"
data_train = torch.load(path)
unzipped = list(zip(*data_train))
x_train = torch.vstack([*unzipped[0]])
y_train = torch.vstack([*unzipped[1]])

In [25]:
m = torch.mean(y_train, 0)
std = torch.std(y_train, 0)
z = torch.where(std == 0) ## checking where std and mean are zero
std[z] = 1.0
y_train_norm = (y_train - m)/std

In [19]:
# print(m, std)
# torch.save(m, "./data/mean.pt")
# torch.save(std, "./data/std.pt")

In [37]:
class Net(torch.nn.Module):

    def __init__(self, inp_size, out_size):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(inp_size, 512)
        self.fc2 = torch.nn.Linear(512, 512)
        self.out = torch.nn.Linear(512, out_size)

    def forward(self, x):
       
        x = torch.tanh(self.fc1(x))
        x = torch.tanh(self.fc2(x))
        x = self.out(x)
        return x


In [40]:
nn = Net(x_train.shape[1], y_train.shape[1])
# nn.load_state_dict(torch.load("./models/test2"))
# nn = nn.cuda()
# x_train = x_train.cuda()
# y_train_norm = y_train_norm.cuda()
# y_train = y_train.cuda()
print(x_train.shape)

lr = 1e-5
eps = int(1e7)
batch_size = 256
optimizer = torch.optim.Adam(nn.parameters(), lr=lr)
loss = torch.nn.L1Loss() #torch.nn.MSELoss() #torch.nn.HuberLoss()

for i in range(eps):
    
    ind = np.random.randint(0,len(x_train), size = batch_size)
    x_train_batch = x_train[ind]
    y_train_batch = y_train_norm[ind]
#     y_train_batch = y_train[ind]

    y_pred = nn(x_train_batch)
    error = loss(y_pred, y_train_batch) 
    print("The iteration number : " + str(i) + " The loss is :" + str(error.cpu().detach().numpy()), end='\r', flush  = True)
    optimizer.zero_grad()
    error.backward()
    optimizer.step()

torch.Size([16000, 17])


In [22]:
nn = nn.cpu()
x_train = x_train.cpu()
y_train_norm = y_train_norm.cpu()

In [23]:
k = np.random.randint(buffer_size)
print(k)
x_des = x_train[k]
viz.viewer["box"].set_object(g.Sphere(0.05), 
                         g.MeshLambertMaterial(
                             color=0xff22dd,
                             reflectivity=0.8))
viz.viewer["box"].set_transform(tf.translation_matrix(x_des[-3:].detach().numpy()))

# x_des = x_train[0]
print(x_des[-3:])

pred_norm = nn(x_des)
pred = pred_norm * std + m
# pred = y_train[k]

if not isvec:
    ioc.weight = torch.nn.Parameter(torch.reshape(pred[0:n_vars**2], (n_vars, n_vars)))
    ioc.x_nom = torch.nn.Parameter(pred[n_vars**2:])
else:
    ioc.weight = torch.nn.Parameter(pred[0:n_vars])
    ioc.x_nom = torch.nn.Parameter(pred[n_vars:])

x_pred = ioc((x_des[:-3]).detach().numpy()) 
x_pred = x_pred.detach().numpy()

plt_des = np.zeros((n_col+1, 3))

for i in range(n_col+1):
    q = x_pred[3*nq*i:3*nq*i + nq]
    dq = x_pred[3*nq*i + nq:3*nq*i + 2*nq]

    pin.forwardKinematics(model, data, q, dq, np.zeros(nv))
    pin.updateFramePlacements(model, data)
    
    plt_des[i] = data.oMf[f_id].translation

    viz.display(q)
    time.sleep(0.05)

788
tensor([0.5589, 0.3821, 0.1869])


In [34]:
k = np.random.randint(buffer_size)
# print(k)
x_in = x_train[k].clone()
x_des = x_in[-3:]
print(x_des)

viz.viewer["box"].set_object(g.Sphere(0.05), 
                         g.MeshLambertMaterial(
                             color=0xff22dd,
                             reflectivity=0.8))
viz.viewer["box"].set_transform(tf.translation_matrix(x_des[-3:].detach().numpy()))


for j in range(10):
    ioc = IOC(n_col, nq, u_max, dt, eps = 1.0, isvec=isvec)
    optimizer = torch.optim.Adam(ioc.parameters(), lr=lr)

    
    pred_norm = nn(x_in)
    pred = pred_norm * std + m
    
    if not isvec:
        ioc.weight = torch.nn.Parameter(torch.reshape(pred[0:n_vars**2], (n_vars, n_vars)))
        ioc.x_nom = torch.nn.Parameter(pred[n_vars**2:])
    else:
        ioc.weight = torch.nn.Parameter(pred[0:n_vars])
        ioc.x_nom = torch.nn.Parameter(pred[n_vars:])

#         print(torch.relu(ioc.weight)*ioc.x_nom)
#         print("--------------------------------------------------")
    x_pred = ioc((x_in[:-3]).detach().numpy()) 
    x_pred = x_pred.detach().numpy()


    for i in range(n_col+1):
        q = x_pred[3*nq*i:3*nq*i + nq]
        dq = x_pred[3*nq*i + nq:3*nq*i + 2*nq]

        pin.forwardKinematics(model, data, q, dq, np.zeros(nv))
        pin.updateFramePlacements(model, data)

        viz.display(q)
        time.sleep(0.05)
    
    x_in[0:2*nq] = torch.tensor(x_pred[-2*nq:])
#     print(x_pred[-nq:])


tensor([-0.5290,  0.3026,  0.0921])


In [41]:
torch.save(nn.state_dict(), "../models/test5")
print("saved ...")

saved ...


In [ ]:
from matplotlib import pyplot as plt

plt.plot(x_pred[2*nq + 1:: 3*nq], label = "joint torque")
plt.legend()
plt.grid()

In [ ]:
plt_des = np.array(plt_des)
plt.plot(plt_des[:,0], label = "x_pos")
plt.grid()
plt.legend()

In [ ]:
plt_des = np.array(plt_des)
plt.plot(plt_des[:,1], label = "y_pos")
plt.grid()
plt.legend()

In [ ]:
plt_des = np.array(plt_des)
plt.plot(plt_des[:,2], label = "z_pos")
plt.grid()
plt.legend()

In [26]:
from mim_data_utils import DataLogger, DataReader
reader = DataReader('test.mds')

for i in range(len(reader.data['joint_positions'])):
    q = reader.data['joint_positions'][i]
    viz.display(q)
#     time.sleep(0.05)

In [22]:
x_train[0]

tensor([ 0.0678,  1.2831,  1.9576,  2.1055,  1.5752, -0.2667,  0.4125,  0.0125,
        -0.3982,  0.0057, -0.0337,  0.3411, -0.1308,  0.0111,  0.6346, -0.4390,
         0.7671])

In [125]:
a = np.array([10,20,30,40])
b = np.array([5,4,3,2])
a*b

array([50, 80, 90, 80])